rsync -avzPcR ./bqpub/inc/def/AssetInfoIF.hpp inc/cxx/
rsync -avzPcR ./bqpub/inc/def/BQConstIF.hpp inc/cxx/
rsync -avzPcR ./bqpub/inc/def/BQDefIF.hpp inc/cxx/
rsync -avzPcR ./bqpub/inc/def/MarketDataIF.hpp inc/cxx/
rsync -avzPcR ./bqpub/inc/def/OrderInfoIF.hpp inc/cxx/
rsync -avzPcR ./bqpub/inc/def/PosInfoIF.hpp inc/cxx/
rsync -avzPcR ./bqpub/inc/def/CommonIPCData.hpp inc/cxx/
rsync -avzPcR ./bqpub/inc/def/PnlIF.hpp inc/cxx/
rsync -avzPcR ./bqpub/inc/def/StgInstInfoIF.hpp inc/cxx/
rsync -avzPcR ./bqpub/inc/def/SymbolInfoIF.hpp inc/cxx/
rsync -avzPcR ./bqpub/inc/BQPub.hpp inc/cxx/
rsync -avzPcR ./bqpub/inc/util/PosSnapshot.hpp inc/cxx/
rsync -avzPcR ./bqpub/inc/util/MarketDataCache.hpp inc/cxx/
rsync -avzPcR ./pub/inc/def/ConstIF.hpp inc/cxx/
rsync -avzPcR ./pub/inc/def/DefIF.hpp inc/cxx/
rsync -avzPcR ./pub/inc/def/StatusCode.hpp inc/cxx/
rsync -avzPcR ./pub/inc/util/Logger.hpp inc/cxx/
rsync -avzPcR ./pub/inc/util/ProgOpt.hpp inc/cxx/
rsync -avzPcR ./pub/inc/util/PchBase.hpp inc/cxx/
rsync -avzPcR ./pub/inc/util/StdExt.hpp inc/cxx/
rsync -avzPcR ./pub/inc/util/Literal.hpp inc/cxx/
rsync -avzPcR ./pub/inc/Pub.hpp inc/cxx/
rsync -avzPcR ./bqipc/inc/SHMHeader.hpp inc/cxx/
rsync -avzPcR ./bqipc/inc/SHMIPCConst.hpp inc/cxx/
rsync -avzPcR ./bqipc/inc/SHMIPCDef.hpp inc/cxx/
rsync -avzPcR ./bqipc/inc/SHMIPCMsgId.hpp inc/cxx/
rsync -avzPcR ./bqipc/inc/SHMIPCPub.hpp inc/cxx/
rsync -avzPcR ./bqipc/inc/SHMIPCTask.hpp inc/cxx/
rsync -avzPcR ./bqstg/bqstgeng-cxx/inc/StgEng.hpp inc/cxx/
rsync -avzPcR ./bqstg/bqstgeng-cxx/inc/StgInstTaskHandlerBase.hpp inc/cxx/
